CapaPresentacionAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;




namespace CapaPresentacionAdmin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Configuraciones()
        {
            return View();
        }  public ActionResult Usuarios()
        {
            return View();
        }
        [HttpGet]
        public JsonResult ListarUsuarios()
        {
        
            List<Usuario> oLista = new List<Usuario>();
            oLista = new CN_Usuarios().Listar();
            //return Json(oLista, JsonRequestBehavior.AllowGet);
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables
        }





        [HttpPost]
        public JsonResult GuardarUsuario(Usuario objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdUsuario == 0)//verifica si es un usuario nuevo pasado por objeto
            {
                resultado = new CN_Usuarios().Registrar(objeto, out mensaje);//devuelve el Id del usuario
            }
            else
            {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);// edita al usurio 
            }
            //devuelve un json con el resultado de los anteriores if llamado igual resultado
            return Json(new { resultado = resultado, mensaje=mensaje }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables

        }



        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";
        //    return View();
        //}

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";
        //    return View();
        //}
    }
}

CapaPresentacionAdmin/Controllers/MercaderiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmin.Controllers
{
    public class MercaderiaController : Controller
    {
        // GET: Mercaderia
        public ActionResult RegistrarEntrada()
        {
            return View();
        }
        public ActionResult ListadoEntrada()
        {
            return View();
        }
        public ActionResult RegistrarSalida()
        {
            return View();
        }
        public ActionResult ListadoSalidas()
        {
            return View();
        }
    }
}

CapaPresentacionAdmin/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CapaPresentacionAdmin/Views/Home/Configuraciones.cshtml
@{
    ViewBag.Title = "Configuraciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Configuraciones</h2>

CapaPresentacionAdmin/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CapaPresentacionAdmin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Pagina Inicial</h1>
    <p class="lead">Bienvenidos a la pagina principal del sistema de Inventario.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Leer mas &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Contactos</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Leer mas &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Mas informacion</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Leer mas &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Almacenamiento Web</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Leer mas &raquo;</a></p>
    </div>
</div>

CapaPresentacionAdmin/Views/Home/Usuarios.cshtml
@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h2>Usuarios</h2>
<ol class="breadcrumb mb-4 mt-3">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Usuarios</li>
</ol>
<div class="card">
    <div class="card-header">
        <i class="fas fa-user me-1"></i>Lista de Usuarios
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Crear Nuevo</button>
            </div>
            <hr />
            <table id="tabla" class="display cell-border" style="width: 100%">
                <thead>
                    <tr>
                        <th>Nombres</th>
                        <th>Apellido</th>
                        <th>Correo</th>
                        <th>Activo</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>







<!-- Modal formulario para el registro de usuarios-->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Usuario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtid" type="hidden" value="0" />
                <div class="row g-2">

                    <div class="col-sm-6">
                        <label for="txtnombres" class="form-label">Nombres</label>
                        <input type="text" class="form-control" id="txtnombres" autocomplete="off">
                    </div> 
                    <div class="col-sm-6">
                        <label for="txtapellidos" class="form-label">Apellidos</label>
                        <input type="text" class="form-control" id="txtapellidos" autocomplete="off">@*autocomplete quita el cargar nombres anteriores*@
                    </div>
                    <div class="col-sm-6">
                        <label for="txtcorreo" class="form-label">Correo</label>
                        <input type="email" class="form-control" id="txtcorreo" placeholder="name@example.com" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">

                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger
                        </div>
                    </div>

                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        var tabladata;
        var filaSeleccionada;
        jQuery.ajax({
            url: '@Url.Action("ListarUsuarios","Home")',
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                //debugger;
                //var texto1 = "hola soy el texto 1"

                console.log(data)
            }
        })



        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarUsuarios","Home")',
                type: "GET",
                dataType:"json",
            },
            "columns": [
                { "data": "Nombres" },
                { "data": "Apellidos" },
                { "data": "Correo" },
                {
                    "data": "Activo", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-success">Si</span>'

                        } else {
                            return '<span class="badge bg-danger">No</span>'
                        }
                    }
                },

                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width":"80px"
                }
            ],
                "language": {
                    "url":"https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"/*cambia el idioma */
            }
        });


        function abrirModal(json) { /* abre el formulario para llenar datos nuevo usuario*/
            $("#txtid").val(0);
            $("#txtnombres").val("");
            $("#txtapellidos").val("");
            $("#txtcorreo").val("");
            $("#cboactivo").val(1);

            $("#mensajeError").hide();//no muestra el cuadro error en el formulario de nuevo usuario

            if (json != null) {//verifica si tiene datos enviados o no
                $("#txtid").val(json.IdUsuario);

                $("#txtnombres").val(json.Nombres);
                $("#txtapellidos").val(json.Apellidos);
                $("#txtcorreo").val(json.Correo);
                $("#cboactivo").val(json.Activo == true ? 1 : 0);
            }

            $("#FormModal").modal("show");
        }









        $("#tabla tbody").on("click", '.btn-editar', function () {
            filaSeleccionada = $(this).closest("tr");//almacena la fila de la tabla seleccionada
            var data = tabladata.row(filaSeleccionada).data(); //almacena los datos leidos en la Variable
            abrirModal(data)
            //console.log(tabladata.row(filaSeleccionada).data());//muestra la fila seleccionada
            //alert("hola")
        })



        $("#tabla tbody").on("click", '.btn-eliminar', function () {
            var usuarioSeleccionado = $(this).closest("tr");//almacena el usuario de la tabla seleccionada
            var data = tabladata.row(usuarioSeleccionado).data(); //almacena el usuario en la Variable

            //usamos sweetalert una variantes pra confirmar la eliminacion
            //muestra un mensaje de alerta para verificar si se borra al usuario.
            swal({
                title: "Estas seguro?",
                text: "Que desea eliminar al usuario!",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                    jQuery.ajax({
                        
                        url: '@Url.Action("EliminarUsuario", "Home")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdUsuario }), //objeto a enviar
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado) {
                                tabladata.row(usuarioSeleccionado).remove().draw();
                            } else {
                                swal("No se pudo eliminar", data.mensaje,"error")
                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }
                });
            });
            //console.log(tabladata.row(filaSeleccionada).data());//muestra la fila seleccionada
            console.log(data);
            //alert("hola")
        })


        function Guardar() {

            var Usuario = {

                IdUsuario: $("#txtid").val(),
                Activo: $("#cboactivo").val()==1? true:false,
                Apellidos: $("#txtapellidos").val(),
                Correo: $("#txtcorreo").val(),
                Nombres: $("#txtnombres").val()
            }


            jQuery.ajax({
                url: '@Url.Action("GuardarUsuario","Home")',
                type: "POST",
                data: JSON.stringify({ objeto: Usuario }), //objeto a enviar
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {//el data es el resultado de retur del homeController linea 58

                    //$(".modal-body").LoadingOverlay("hide");
                    //console.log(data)

                    // USUARIO NUEVO
                    if (Usuario.IdUsuario == 0) {

                        if (data.resultado != 0) {
                            Usuario.IdUsuario = data.resultado;
                            tabladata.row.add(Usuario).draw(false);
                            $("#FormModal").modal("hide");

                        } else {
                            //alert(data.mensaje);
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                    //Usuario Editar
                    else {
                        if (data.resultado) {
                            tabladata.row(filaSeleccionada).data(Usuario).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                    //console.log(error)
                },
                beforeSend: function () {
                    //muestra la carga mientras se realiza la operacion de actualizacion de datos del usuario
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size:14
                    })
                }
            });
        }
    </script>

} 

CapaPresentacionAdmin/Views/Mercaderia/ListadoEntrada.cshtml
@{
    ViewBag.Title = "ListadoEntrada";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado Entrada</h2>

CapaPresentacionAdmin/Views/Mercaderia/ListadoSalidas.cshtml
@{
    ViewBag.Title = "ListadoSalidas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado Salidas</h2>

CapaPresentacionAdmin/Views/Mercaderia/RegistrarEntrada.cshtml
@{
    ViewBag.Title = "RegistrarEntrada";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Entrada</h2>

CapaPresentacionAdmin/Views/Mercaderia/RegistrarSalida.cshtml
@{
    ViewBag.Title = "RegistrarSalida";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Salida</h2>

CapaPresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">ADMINISTRADOR</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Ajustes</a></li>
                    <li><a class="dropdown-item" href="#!">Correo Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Panel Principal
                        </a><a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-alt"></i></div>
                            Usuarios
                        </a>
                        <a class="nav-link" href="@Url.Action("Configuraciones","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-toolbox"></i></div>
                            Configuraciones
                        </a>
                        <div class="sb-sidenav-menu-heading">Productos</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-barcode"></i></div>
                            Entradas
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("RegistrarEntrada","Mercaderia")">Registrar Entradas</a>
                                <a class="nav-link" href="@Url.Action("ListadoEntrada","Mercaderia")">Listado Entrada</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-cart-arrow-down"></i></div>
                            Salidas
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Registrar Salida
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Articulos</a>
                                        <a class="nav-link" href="register.html">Insumos</a>
                                        <a class="nav-link" href="password.html">Papeleria</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Listado Salidas
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">Historico</a>
                                        <a class="nav-link" href="404.html">Semanal</a>
                                        <a class="nav-link" href="500.html">Diario</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Usuarios</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-check"></i></div>
                            Clientes
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Proveedores
                        </a>
                        <div class="sb-sidenav-menu-heading">Dashboard</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Reportes
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Analisis
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Usted a iniciado como:</div>
                    Administrador
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Website 2022</div>
                        <div>
                            <a href="#">Politica de privacidad</a>
                            &middot;
                            <a href="#">Terminos &amp; Condiciones</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>